### ISSUE TITLE
Relationships for taxonomy

### ISSUE THREAD

**Issue by dlschwartz** [srophe/draft-data#15]
@wsalesky I managed to get basics into the spreadsheet and transform the .tsv into TEI records. Those are at: https://github.com/srophe/draft-data/tree/master/data/keywords/relationshipsTaxonomy. I think the transform went well but there might be a couple of things that could be handled a bit differently. Please let me know what you think.

I have created a few relationships to make this work. There is now a "relationships" record and everything nests under that entry. 

What our "RDF for SPEAR" spreadsheet called "categories" are now their own entries that have a skos:broadMatch with "relationships": i.e., https://github.com/srophe/draft-data/blob/master/data/keywords/relationshipsTaxonomy/clerical-relationships.xml#L130. I've needed to add a couple of categories as well.

All the remaining entries that aren't "categories" nest under one (or more) of the "categories": i.e., https://github.com/srophe/draft-data/blob/master/data/keywords/relationshipsTaxonomy/clergy-for.xml#L130. 

All entries now have a Syriaca.org URI: i.e., https://github.com/srophe/draft-data/blob/master/data/keywords/relationshipsTaxonomy/clergy-for.xml#L134.

Every TEI record includes as well an idno that is the namespace:term used in the SPEAR records: i.e., https://github.com/srophe/draft-data/blob/master/data/keywords/relationshipsTaxonomy/clergy-for.xml#L135.

Please let me know if you have any questions Winona. Thanks!

**Comment by nathangibson** [comment]
Sorry we never discussed how to tweak the transform. Do we still need to do that or did you figure it out?
