### ISSUE TITLE
Location of Canonical Works TEI

### ISSUE THREAD

**Issue by davidamichelson** [srophe/draft-data#5]
Hi @wsalesky ,

I'm confused as to where the canonical version of works are. The version that is on the Dev server does not seem to be anywhere in the repository.

When you are able, please upload a final copy of the TEI to draft-data/works/tei

Thanks,
Dave

**Comment by wsalesky** [comment]
Hi Dave, 
Git tells me the files on my machine are the same as the ones on the github. What is different? (So I can troubleshoot.)

**Comment by davidamichelson** [comment]
This version still has the edition numbers in it:
https://github.com/srophe/draft-data/blob/master/data/works/tei/297.xml#L220
but maybe that is okay?

**Comment by wsalesky** [comment]
Yes that is fine, I will rerun the xquery after the updates.

**Comment by davidamichelson** [comment]
Okay, this afternoon I will make afew more edits to the Saints Persons
XSLT. Can you make the other XSLT changes I mention in the various issues?

Thanks

**Comment by wsalesky** [comment]
Yes, I will try to get them all done today.
-Winona

**Comment by wsalesky** [comment]
@davidamichelson , when you make your changes can you comment out the  BSH id generation? That will save me a step in the xquery, and I will use the citedrange to do the match. 

Thanks!

**Comment by davidamichelson** [comment]
Where did we end up on this? I did not see this and did not comment it out
alas. Let me know what you need me to do if anything.

**Comment by wsalesky** [comment]
It is fine, my script will delete it. I am ironing out the final details
today, should be able to push the new data to github soonish.

**Comment by davidamichelson** [comment]
Thanks!
