### ISSUE TITLE
Change in Works Data

### ISSUE THREAD

**Issue by davidamichelson** [srophe/draft-data#6]
Assuming that we are done with the Works XSLT and the TEI is final, please find and replace this sentence:
`<bibl xml:id="witness8">The manuscript sources for an edition above is unknown.</bibl>`

Original:
`The manuscript sources for an edition above is unknown.`
Changed:
`The manuscript witnesses for edition [d] are undetermined.`
Note: the digit here should be taken from the digit in the xml:id="witness8"

**Comment by wsalesky** [comment]
This change has been made to the xquery. Will take effect next time the I data is run.
