### ISSUE TITLE
Multiple occurrences of the same URI

### ISSUE THREAD

**Issue by dlschwartz** [srophe/draft-data#8]
Can we limit the URI output to only one occurrence of each URI? In many cases we get multiple occurrences of the same URI. I'm guessing this is caused by having several name variants with the hit for the NER (i.e. the input list has John and one URI has the name variants John, John Chrysostom, John of Constantinople, etc. so it returns the URI several times).

**Comment by wsalesky** [comment]
Yes, I will look into it.

**Comment by wsalesky** [comment]
@dlschwartz How does this new version look?

**Comment by dlschwartz** [comment]
Perfect! Thanks.

On Wed, Oct 21, 2015 at 9:58 PM, Winona Salesky notifications@github.com
wrote:

> @dlschwartz https://github.com/dlschwartz How does this new version
> look?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srophe/draft-data/issues/8#issuecomment-150092215.

## 

Dr. Daniel L. Schwartz
Assistant Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture http://idhmc.tamu.edu/

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

_Paideia and Cult http://chs.harvard.edu/CHS/article/display/5813:
Christian Initiation in Theodore of Mopsuestia_ (Center for Hellenic
Studies, 2013)
www.syriaca.org http://syriaca.org/

**Comment by wsalesky** [comment]
@dlschwartz,  @nathangibson and I have been trying to refine this for the BHSE data, and I have run a few versions for him. One that matches only headwords, and one that matches all name variants. Your current copy only matches headwords. Would you like a version that matches all name variants to compare? This new version of the script is a bit more flexible, so it is easy to amend.

**Comment by dlschwartz** [comment]
All name variants would be best. Our headword can sometimes be an
unconventional transliteration but we regularly capture more common
transliterations among the name variants. Thanks Winona.

On Thu, Oct 22, 2015 at 9:42 AM, Winona Salesky notifications@github.com
wrote:

> @dlschwartz https://github.com/dlschwartz, @nathangibson
> https://github.com/nathangibson and I have been trying to refine this
> for the BHSE data, and I have run a few versions for him. One that matches
> only headwords, and one that matches all name variants. Your current copy
> only matches headwords. Would you like a version that matches all name
> variants to compare? This new version of the script is a bit more flexible,
> so it is easy to amend.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srophe/draft-data/issues/8#issuecomment-150245945.

## 

Dr. Daniel L. Schwartz
Assistant Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture http://idhmc.tamu.edu/

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

_Paideia and Cult http://chs.harvard.edu/CHS/article/display/5813:
Christian Initiation in Theodore of Mopsuestia_ (Center for Hellenic
Studies, 2013)
www.syriaca.org http://syriaca.org/

**Comment by wsalesky** [comment]
Done. You can compare  the two. #3 uses all name variants.
-Winona

**Comment by dlschwartz** [comment]
Looks great! Thanks.

On Thu, Oct 22, 2015 at 9:51 AM, Winona Salesky notifications@github.com
wrote:

> Done. You can compare the two. #3 uses all name variants.
> -Winona
> 
> On Thu, Oct 22, 2015 at 10:46 AM, Daniel Schwartz <
> notifications@github.com>
> wrote:
> 
> > All name variants would be best. Our headword can sometimes be an
> > unconventional transliteration but we regularly capture more common
> > transliterations among the name variants. Thanks Winona.
> > 
> > On Thu, Oct 22, 2015 at 9:42 AM, Winona Salesky <
> > notifications@github.com>
> > wrote:
> > 
> > > @dlschwartz https://github.com/dlschwartz, @nathangibson
> > > https://github.com/nathangibson and I have been trying to refine
> > > this
> > > for the BHSE data, and I have run a few versions for him. One that
> > > matches
> > > only headwords, and one that matches all name variants. Your current
> > > copy
> > > only matches headwords. Would you like a version that matches all name
> > > variants to compare? This new version of the script is a bit more
> > > flexible,
> > > so it is easy to amend.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/srophe/draft-data/issues/8#issuecomment-150245945
> > > .
> > 
> > ## 
> > 
> > Dr. Daniel L. Schwartz
> > Assistant Professor of History
> > Associate Director of the Initiative for Digital Humanities, Media, and
> > Culture http://idhmc.tamu.edu/
> > 
> > Texas A&M University
> > 4236 TAMU
> > College Station, Texas 77843-4236
> > 
> > _Paideia and Cult http://chs.harvard.edu/CHS/article/display/5813:
> > Christian Initiation in Theodore of Mopsuestia_ (Center for Hellenic
> > Studies, 2013)
> > www.syriaca.org http://syriaca.org/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/srophe/draft-data/issues/8#issuecomment-150248651.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srophe/draft-data/issues/8#issuecomment-150250919.

## 

Dr. Daniel L. Schwartz
Assistant Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture http://idhmc.tamu.edu/

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

_Paideia and Cult http://chs.harvard.edu/CHS/article/display/5813:
Christian Initiation in Theodore of Mopsuestia_ (Center for Hellenic
Studies, 2013)
www.syriaca.org http://syriaca.org/

**Comment by wsalesky** [comment]
Great!
