### ISSUE TITLE
place name NER for SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/draft-data#9]
Hi Winona. I've uploaded a file into the SPEAR draft-data folder with a list of place names from Severus' letters. Whenever you get the chance it would be great if you could run NER on that. Thank you!

**Comment by wsalesky** [comment]
Done. Remember you can also run it yourself here:
http://wwwb.library.vanderbilt.edu:8080/exist/apps/srophe-forms/ner.html

**Comment by dlschwartz** [comment]
Sorry, I forgot about that. Thanks Winona.

**Comment by wsalesky** [comment]
No problem!
